Add support for using server-icon.png as favIcon
vincss/mcsleepingserverstarter pull request #156
Opened 2023-03-29 07:59 UTC by markmetcalfe

Currently the only way to override the default server icon is to specify a large base64 string in the settings config file. This is annoying as it requires you to manually convert the image you want into base64, and then place the string into the file which is bad for performance - I noticed VS Code was slower when opening the file.

With this change, you can simply just add
```
useServerIcon: true
```
into the settings yml, and it will load the `server-icon.png` file in the minecraft server directory, which is much more convenient.

2023-03-29 08:32 UTC, vincss requested changes

2023-03-29 08:32 UTC, vincss commented on src/sleepingHelper.ts
> +    return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGHRFWHRTb
Keep a constant outside of the function.

2023-03-29 08:32 UTC, vincss commented on src/sleepingSettings.ts
> +    useServerIcon?: boolean,
Maybe put a string to specify another favicon.

2023-03-29 10:05 UTC, markmetcalfe commented on src/sleepingHelper.ts
> +    return 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGHRFWHRTb
Done

2023-03-29 10:06 UTC, markmetcalfe commented on src/sleepingSettings.ts
> +    useServerIcon?: boolean,
Done - added a new setting: `favIconPath` so you can specify a path other than `server-icon.png`

2023-03-29 11:12 UTC, vincss commented on src/sleepingHelper.ts
> +        favIconPath = `${minecraftDir}/server-icon.png`;
you should use favIconPath here

2023-03-29 19:16 UTC, markmetcalfe commented on src/sleepingHelper.ts
> +        favIconPath = `${minecraftDir}/server-icon.png`;
Done - have removed the `userServerIcon` setting

2023-03-29 19:17 UTC, markmetcalfe commented on src/sleepingSettings.ts
> +    favIconPath?: string,
Done - have removed the `useServerIcon` parameter in favour of just having `favIconPath`

2023-03-29 19:18 UTC, markmetcalfe commented
@vincss I've resolved the conflicts with the MOTD changes that were merged, and have made the changes you suggested. Once this is merged, could you run a release? I don't have any further contributions to make for now - I want to get a docker container working which I will need a release for.

2023-03-30 08:03 UTC, markmetcalfe commented on src/sleepingHelper.ts
> +    if (!favIconPath.startsWith('/') && !favIconPath.startsWith('\\')) {
Done

2023-03-30 08:04 UTC, vincss approved these changes

2023-03-30 08:11 UTC, merged